version: '3'
services:
  batch:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/src
    tty: true
    stdin_open: true

networks:
  default:
    external:
      name: tebiki-web_default