AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  insert-mf-data-to-aurora-severless

  Sample SAM Template for insert-mf-data-to-aurora-severless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300

Resources:
  ServerlessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: insert_function/
      Handler: app.lambda_handler
      Runtime: python3.6
      Layers:
        - !Ref ServerlessLayer
  ServerlessLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layer/
